---
  - name: first-playbook
    hosts: all
    become: yes
    tasks:
      - name: ensure byobu is there
        apt:
          name: byobu
          state: latest
        when: ansible_distribution == "Ubuntu" 

      - name: ensure byobu is there
        dnf:
          name: byobu
          state: latest
        when: ansible_distribution in ["CentOS", "Fedora"]
