---

- hosts: all
  become: yes
  tasks:
  
  - name: run updates in CentOS and Ubuntu
    package:
        update_cache: yes

- hosts: web_servers
  become: yes
  tasks:

  - name: install apache and php for ubuntu 
    apt:
     name:
        - apache2
        - libapache2-mod-php
     state: latest
    when: ansible_distribution == "Ubuntu"     

  - name: install apache and php in rpm systems
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["CentOS","Fedora"]
  
  - name: start httpd (CentOS)
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change email adress for admin user
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin adminuser@companydomain.com
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restart apache after any change
    service:
      name: httpd
      state: restarted
    when: httpd.changed
  ###
  - name: copy sample file to web-server
    copy:
      src: sample-web-page.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  ###
  - name: copy sample file to web-server
    copy:
      dest: /var/www/html/php-info.php
      content: "<?php \n
              // Show all information, defaults to INFO_ALL \n
              phpinfo(); \n
              ?>"
      owner: root
      group: root
      mode: 0644
  